EXPORT loan := MODULE

    MyRecord := RECORD
        string id;
        string member_id;
        string loan_amnt; 
        string funded_amnt;  
        string funded_amnt_inv;  
        string term;
        string int_rate;
        string installment;  
        string grade ; 
        string sub_grade;  
        string emp_title ; 
        string emp_length; 
        string home_ownership;  
        string annual_inc;  
        string verification_status;  
        string issue_d ; 
        string loan_status;  
        string pymnt_plan ; 
        string url ; 
        string desc ; 
        string purpose ; 
        string title ; 
        string zip_code;  
        string addr_state;  
        string dti;  
        string delinq_2yrs;  
        string earliest_cr_line;  
        string fico_range_low;  
        string fico_range_high;  
        string inq_last_6mths;  
        string mths_since_last_delinq;  
        string mths_since_last_record;  
        string open_acc;  
        string pub_rec;  
        string revol_bal ; 
        string revol_util ; 
        string total_acc;  
        string initial_list_status ; 
        string out_prncp  ;
        string out_prncp_inv ; 
        string total_pymnt ; 
        string total_pymnt_inv;  
        string total_rec_prncp;  
        string total_rec_int ; 
        string total_rec_late_fee ; 
        string recoveries  ;
        string collection_recovery_fee ; 
        string last_pymnt_d  ;
        string last_pymnt_amnt  ;
        string next_pymnt_d ;
        string last_credit_pull_d  ;
        string last_fico_range_high ; 
        string last_fico_range_low ; 
        string collections_12_mths_ex_med ; 
        string mths_since_last_major_derog;  
        string policy_code;  
        string application_type ; 
        string annual_inc_joint  ;
        string dti_joint  ;
        string verification_status_joint  ;
        string acc_now_delinq  ;
        string tot_coll_amt  ;
        string tot_cur_bal  ;
        string open_acc_6m  ;
        string open_act_il  ;
        string open_il_12m  ;
        string open_il_24m  ;
        string mths_since_rcnt_il;  
        string total_bal_il  ;
        string il_util  ;
        string open_rv_12m  ;
        string open_rv_24m  ;
        string max_bal_bc  ;
        string all_util  ;
        string total_rev_hi_lim  ;
        string inq_fi  ;
        string total_cu_tl  ;
        string inq_last_12m  ;
        string acc_open_past_24mths;  
        string avg_cur_bal  ;
        string bc_open_to_buy ; 
        string bc_util  ;
        string chargeoff_within_12_mths  ;
        string delinq_amnt  ;
        string mo_sin_old_il_acct ; 
        string mo_sin_old_rev_tl_op ; 
        string mo_sin_rcnt_rev_tl_op  ;
        string mo_sin_rcnt_tl  ;
        string mort_acc  ;
        string mths_since_recent_bc  ;
        string mths_since_recent_bc_dlq ; 
        string mths_since_recent_inq  ;
        string mths_since_recent_revol_delinq ; 
        string num_accts_ever_120_pd  ;
        string num_actv_bc_tl  ;
        string num_actv_rev_tl  ;
        string num_bc_sats  ;
        string num_bc_tl  ;
        string num_il_tl  ;
        string num_op_rev_tl  ;
        string num_rev_accts  ;
        string num_rev_tl_bal_gt_0  ;
        string num_sats  ;
        string num_tl_120dpd_2m  ;
        string num_tl_30dpd  ;
        string num_tl_90g_dpd_24m  ;
        string num_tl_op_past_12m  ;
        string pct_tl_nvr_dlq  ;
        string percent_bc_gt_75 ; 
        string pub_rec_bankruptcies ; 
        string tax_liens ; 
        string tot_hi_cred_lim  ;
        string total_bal_ex_mort  ;
        string total_bc_limit  ;
        string total_il_high_credit_limit ; 
        string revol_bal_joint  ;
        string sec_app_fico_range_low ; 
        string sec_app_fico_range_high ; 
        string sec_app_earliest_cr_line;  
        string sec_app_inq_last_6mths ;
        string sec_app_mort_acc  ;
        string sec_app_open_acc  ;
        string sec_app_revol_util ; 
        string sec_app_open_act_il  ;
        string sec_app_num_rev_accts  ;
        string sec_app_chargeoff_within_12_mths  ;
        string sec_app_collections_12_mths_ex_med ; 
        string sec_app_mths_since_last_major_derog ; 
        string hardship_flag  ;
        string hardship_type  ;
        string hardship_reason  ;
        string hardship_status ; 
        string deferral_term  ;
        string hardship_amount  ;
        string hardship_start_date ; 
        string hardship_end_date  ;
        string payment_plan_start_date ; 
        string hardship_length  ;
        string hardship_dpd  ;
        string hardship_loan_status ; 
        string orig_projected_additional_accrued_interest ; 
        string hardship_payoff_balance_amount;
        string hardship_last_payment_amount ; 
        string disbursement_method;  
        string debt_settlement_flag  ;
        string debt_settlement_flag_date  ;
        string settlement_status  ;
        string settlement_date  ;
        string settlement_amount ;
        string settlement_percentage ; 
        string settlement_term ; 
    END;

    EXPORT file := DATASET('~loan::nemo::train::accepted_2007_to_2018q4-1.csv', MyRecord, CSV(HEADING(1)));

    EXPORT MyData := RECORD
        UNSIGNED4 RecID;
        UNSIGNED8 id;
        DECIMAL8_2 loan_amnt; 
        DECIMAL8_2 funded_amnt;
        DECIMAL4_2 int_rate;
        DECIMAL4_2 installment; 
        DECIMAL8_2 annual_inc; 
        DECIMAL4_2 dti; 
        UNSIGNED8 open_acc; 
        DECIMAL8_2 revol_bal; 
        DECIMAL4_2 revol_util;
        UNSIGNED8 total_acc; 
        DECIMAL8_2 total_rec_int;
        DECIMAL4_2 total_rec_late_fee;
        UNSIGNED1 loan_status; 

    END;

END;